import Head from "next/head";
import Body from "./container/Body";
import Header from "./container/Header";
import { useState } from "react";

export default function Home() {
  const [dark, setDark] = useState(false);
  const handleDark = () => {
    setDark((prev) => !prev);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${dark ? "dark" : "light"}`}>
        <Header dark={dark} setDark={setDark} handleDark={handleDark} className />
        <Body />
      </main>
    </>
  );
}
